apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
# Enable experimental kubernetesGateways: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml#L130
spec:
  valuesContent: |-
    providers:
      kubernetesGateway:
        enabled: true
        experimentalChannel: true
    experimental:
      kubernetesGateway:
        enabled: true
    ports:
      minecraft:
        port: 25565
        exposedPort: 25565
        protocol: TCP